### PR TITLE
Leaderboard: final touches

### PR DESCRIPTION
**Pull request by mateo951**
- Added The Legend of Zelda theme to the leaderboard
  - Added background
  - Added font to project
  - Added styling to boxes

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
Hi @mateo951 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not use the correct gitflow. According to the requirement, `Pull Request is made from the “feature branch” into the main branch`.
Please se[e this document on how to change the base branch.](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mateo951** [comment]
Hey @george-shammar,

I don't quite understand why is invalid. In Gitflow concept, you should never go straight to the main as you are telling me. Creating a request straight to the main is considered a bad practice in Gitflow. That flow of work is Github Flow 😥

Thanks in advance!

**Comment by george-shammar** [comment]
Hello @mateo951 , We chatted on slack. I am just seeing this message. Hope I was able clarify your objection? We are following the project's requirement and I was able to provide you screenshots where it was speicifically stated. You can always seek a second opinion in this regard.

**Comment by mateo951** [comment]
The problem is that the rubric that you have for the project is checking for GitHub flow instead of Gitflow as the project requires 😥 The rubric should be updated to avoid future similar issues!

image (1)

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUESTED :recycle:

Hi, @mateo951 

Great work on implementing the changes requested by the previous reviewer, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Changes required :writing_hand: 
  - The card is not displaying the sent data, kindly make sure a user is able to check for the data sent in the card
  - Kindly, fix the data that are going beyond the card as you can see on the below image.
arr22
       
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by mateo951** [comment]
Hey @Emmyn5600, 

Thanks for your feedback! All of the requirements are already implemented to the project 😎

**Review by oxenprogrammer — APPROVED** [review]
Hi @mateo951 , 

Good effort on working on the requested changes by the previous Code Reviewers.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
